### ISSUE TITLE
Building on macOS Mojave

### ISSUE THREAD

**Issue by mmahfoudi** [13-37-org/infnoise#16]
Hello guys,

I am trying to build on Mojave but here the error I receive : 
```
Undefined symbols for architecture x86_64:
  "_inmWriteEntropyEnd", referenced from:
      _main in infnoise.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [infnoise] Error 1
```
Does anybody face this kind of error ? How can I solve it ?
Thank you.

**Comment by manuel-domke** [comment]
Hi,
this seems to be caused by a recent change. Added a possible fix in commit 9175803. 

No MacBook at hand right now, but I'll test in a few hours. Maybe you'll be faster.

**Comment by mmahfoudi** [comment]
I just compiled and no more errors.
I executed the binary and so far it seems to be working as expected :)

Thank you.

**Comment by manuel-domke** [comment]
Awesome. Thanks for reporting!
