### ISSUE TITLE
Is sytemd needed?

### ISSUE THREAD

**Issue by FantasyCookie17** [13-37-org/infnoise#21]
If there were a forum/IRC or anything, I'd ask there, but afaict there is none. The packages automatically generate a systemd service. So it won't be compatible with other init systems like OpenRC or runit? Or am I misunderstanding anything about init daemon services or the infnoise driver? Will this differ when compiling from source (because e.g. Gentoo and Void don't have suitable packages anyway)?

**Comment by manuel-domke** [comment]
Hi,
the systemd service is not required at all. 
It's just for convenience: to start the driver when the device is plugged in.

There's also an openrc config in the repo: https://github.com/13-37-org/infnoise/blob/master/software/init_scripts/infnoise.gentoo.openrc, but I don't think it's used in any build steps so far. 
The install target however installs the systemd files and while I guess this doesn't cause any issues on systems with openrc, it should probably be changed.
