### ISSUE TITLE
Removal of FTDI library files for Windows needed

### ISSUE THREAD

**Issue by jj1bdx** [13-37-org/infnoise#9]
FTDI library files are obviously under the copyright of FTDI and not in the public domain.
Removing their files under `software/VisualStudio/ftdi` and replacing it by a README.md file like this will be a better solution:
https://github.com/jj1bdx/infnoise-windows/blob/master/VisualStudio/ftdi/README.md

**Comment by MartyMacGyver** [comment]
I did this on https://github.com/MartyMacGyver/infnoise/tree/mff-update-windows-build-and-functionality as well - I'm awaiting some input as to where I ought to be submitting my changes (here or the waywardgeek origin?)

**Comment by MartyMacGyver** [comment]
Resolved via the merge above.

**Comment by jj1bdx** [comment]
@MartyMacGyver LGTM and thanks!
